### ISSUE TITLE
Implement NEAT Trainer

### ISSUE THREAD

**Issue by jbeemster** [NES-NN/OpenAI-Testbed#1]
Should be following the same logic as our C# implementation roughly - run infinite length and kill sessions based of of Mario not moving forward.

**Comment by LoicNyssen** [comment]
This is done. 
FYI:
To train a new network you would run something like this:
`python3 Train.py --num-cores=4 --generations=10`
where num-cores is how many Emulators you want it to spin up at once, and generations is how many generations you want to test. It will just exit when it is done. 

If you want to continue training from a previous session, same as before. but add
`python3 Train.py --num-cores=4 --generations=10 --checkpoint=checkpoint`
Where checkpoint is the name of the save file. hard coded as checkpoint for the moment.
