### ISSUE TITLE
SMB Gym: add ability to close fceux on reset

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/OpenAI-Testbed#12]
When training a network, heaps of fceux are left open, and i suspect may be why the training seems to crash randomly.

**Comment by LoicNyssen** [comment]
Don't think this is fixed. Just checked my current training session, there is 7 windows open, where the max should be 4.

**Comment by jbeemster** [comment]
I am not sure multi-threading + named pipes + shell processes is entirely fixable.  We would likely need to re-write all of the code for managing spinning up and killing the emulator.

**Comment by LoicNyssen** [comment]
We are going to have to do something. have a look at this
`root     15634 88.4  0.7 223212 28472 pts/2    R+   18:34  15:03 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     26050 79.9  0.7 223052 28424 pts/2    R+   18:45   3:39 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     28730 59.9  0.7 223448 29276 pts/2    R+   18:48   0:56 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     29264  0.0  0.0  11308  2540 pts/3    S+   18:49   0:00 watch ps aux |grep /usr/games/fceux
root     29524  4.4  0.7 223916 29196 pts/2    S+   18:49   0:01 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     29795  5.5  0.7 223444 29268 pts/2    S+   18:50   0:01 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     30064  8.2  0.6 222788 28220 pts/2    R+   18:50   0:00 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua
root     30099  7.1  0.7 222784 28420 pts/2    S+   18:50   0:00 /usr/games/fceux --xscale 2 --yscale 2 -f 0 --loadlua`

As you can see the 3 that didn't close are using a huge percentage of the cpu. and it basically slows the training down to a complete standstill.

**Comment by LoicNyssen** [comment]
Could someone else do some testing to see if the qutrino fork of gym-super-mario actually fixes the closing fcuex issue. I just ran some tests to execute the command manually and it didn't work. 
and while looking into it I noticed that the stat of the processes isn't consistent, as in the both some active fceux windows and some stuck ones have the same STAT code. so, I might be missing something, but i am unable to definitively tell which process is an active one and which one isn’t. 

Anyway, can someone else please try to replicate my findings…
