### ISSUE TITLE
Docker: add ability to run training in headless mode

### ISSUE THREAD

**Issue by jbeemster** [NES-NN/OpenAI-Testbed#6]

**Comment by jbeemster** [comment]
So have looked into this - there seems to be a way to use Xvfb as way to run the training in headless mode but it seems to get stuck on some pipe calls within the environment code.  Essentially I get one run in and then it stalls on the reset function.

**Comment by LoicNyssen** [comment]
Have you tried to set the display environment variable? That has worked for me so far. 
and to clean up after a training session i just run
`for pid in $(ps -ef | grep "/usr/games/fceu" | awk '{print $2}'); do kill -9 $pid; done`

**Comment by jbeemster** [comment]
Which display var is that @LoicNyssen ?

**Comment by LoicNyssen** [comment]
So, i have been running it headless like this. 
first i started a byobu session, allowing me to disconnect and stop my training session. 
then i export the display to the one you setup, in the dockerfile
`# export display=:1`
then starting the training
`# python3 Train.py --generations 20 --save-file test1 --num-cores 4` 

et voilà, detachable headless training.

**Comment by jbeemster** [comment]
This is done via wooey and working well!
